[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "20.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
bcrypt = "0.10.1"
form_urlencoded = "1.0"
thiserror = "1.0"
